services:
  nessus01-dedy-irawan-dedycated-com:
    image: tenableofficial/nessus
    container_name: nessus01-dedy-irawan-dedycated-com
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "8801:8834"
    restart: unless-stopped
  nessus02-naga-api-bersatu:
    image: tenableofficial/nessus
    container_name: nessus02-naga-api-bersatu
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "8802:8834"
    restart: unless-stopped