services:
  nessus01-dedy-irawan-dedycated-com:
    image: tenableofficial/nessus
    container_name: nessus01-dedy-irawan-dedycated-com
    environment:
      - TZ=Asia/Jakarta
    ports:
      - "8801:8834"
    restart: unless-stopped
